### ISSUE TITLE
Can't import util.colors

### ISSUE THREAD

**Issue by Caesurus** [miaouPlop/gdb-helper#1]
I like the project and am excited to try it out. Just FYI, I did a fresh install following the instructions but get the following:

```
code@hackbox:~$ python                                                          
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
>>> from gdbhelper import Peda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/gdbhelper/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/gdbhelper/peda.py", line 5, in <module>
ImportError: No module named util.colors
>>> 
```
Interesting thing is:

If I do the following PYTHONPATH, I am able to proceed:
```
code@hackbox:~$ export PYTHONPATH=/home/code/gdb-helper/gdbhelper/
code@hackbox:~$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
>>> from gdbhelper import Peda
>>>
``` 

Just thought I'd mention it here. And thanks for the project :)

**Comment by miaouPlop** [comment]
Hi Caesurus!

Thank you for your interest! Do not hesitate to contact me and tell me what you think of the tool!

Regarding your issue, I never experienced it but I'll try to fix it as soon as I have some free time!
